
@startuml
interface 夹胸
    abstract 哑铃飞鸟 
    哑铃飞鸟 --|> 夹胸
        静力单侧哑铃飞鸟 --|> 哑铃飞鸟
        上斜哑铃飞鸟 --|> 哑铃飞鸟
    ' ---
    abstract 器械夹胸 
    器械夹胸 --|> 夹胸
        坐姿器械夹胸 --|>器械夹胸
        屈臂器械夹胸 --|>器械夹胸
        直臂器械夹胸 --|>器械夹胸
    ' ---
    interface 拉索夹胸
    拉索夹胸 --|> 夹胸
            abstract 静力单侧拉索夹胸 
            静力单侧拉索夹胸 --|> 拉索夹胸
            反手静力单侧拉索夹胸 --|> 静力单侧拉索夹胸
            正手静力单侧拉索夹胸 --|> 静力单侧拉索夹胸

@enduml
@startuml
interface 卧推 
    abstract 杠铃卧推 
    杠铃卧推 --|>卧推
    平板杠铃卧推 --|> 杠铃卧推
    上斜杠铃卧推 --|> 杠铃卧推

    abstract 哑铃卧推 
    哑铃卧推 --|>卧推
    健身球哑铃卧推 --|> 哑铃卧推
    平板哑铃卧推 --> 哑铃卧推
    上斜哑铃卧推 --> 哑铃卧推

    abstract 器械卧推 
    器械卧推 --|>卧推
    平板器械卧推 --|>器械卧推
    上斜器械卧推 --|>器械卧推
@enduml
@startuml
interface 俯卧撑 
    钻石俯卧撑 --|> 俯卧撑
    标准俯卧撑 --|>俯卧撑
    下斜窄距俯卧撑 --|>俯卧撑
@enduml
@startuml
interface 胸部拉伸
    单侧PNF胸部拉伸 --|> 胸部拉伸
@enduml
 
@startuml
class 胸不一样大 {
    正手静力单侧拉索夹胸
    反手静力单侧拉索夹胸
    蝴蝶机夹胸 
    平板杠铃卧推 
    上斜杠铃卧推 
    ---
    标准俯卧撑
    下斜窄距俯卧撑
    健身球哑铃卧推
    静力单侧哑铃飞鸟 
}

class 菲尔西斯胸部束形 {
    上斜杠铃卧推
    上斜哑铃卧推
    上斜哑铃飞鸟
    上斜哑铃飞鸟
    平板器械卧推
    平板哑铃卧推
    坐姿蝴蝶机夹胸
    拉索夹胸
}

class 新手入门胸部束形 {
    器械卧推
    上斜器械卧推
    拉索夹胸
    蝴蝶机夹胸
    单侧PNF胸部拉伸
}
@enduml

@startuml
interface 高位下拉 
    反手高位下拉--|> 高位下拉
    正手宽握高位下拉 --|> 高位下拉
    直臂下拉 --|> 高位下拉
    直背高位下拉 -->高位下拉
interface 引体向上
    反手窄握引体向上--|>引体向上
interface 耸肩
    哑铃耸肩 --|> 耸肩
    杠铃耸肩 --|> 耸肩
interface 平举
    杠铃窄握前平举 --|> 平举
    L侧平举 --|>平举
    俯身哑铃侧平举 --|>平举

interface 划船
    哑铃划船 --|> 划船
    杠铃划船 --|> 划船
    反手俯身哑铃划船 --|>哑铃划船
    杠铃俯身划船 --|> 杠铃划船
    对握器械划船 --|> 杠铃划船
    哑铃正手划船 --|> 杠铃划船

    interface 十字挺身

    class 反向飞鸟
    外旋反向器械飞鸟 -->反向飞鸟
    外旋反向哑铃飞鸟 -->反向飞鸟
    内旋反向器械飞鸟 -->反向飞鸟
    内旋反向哑铃飞鸟 -->反向飞鸟
    反向器械飞鸟 -->器械飞鸟

    interface 平举
        俯身哑铃侧平举 --|>平举






@enduml

@startuml
class 背部 {
    - 反手高位下拉
    - 反手窄握引体向上 
    - 正手宽握高位下拉
    + 反手杠铃划船
    + 正手杠铃划船
}
class 背阔肌 {
    - 反手高位下拉
    - 反手窄握引体向上 
    - 反手俯身哑铃划船
    + 反手杠铃划船
}

class 斜方肌上部 {
    - 哑铃耸肩
    - 杠铃耸肩
    - 杠铃窄握前平举
}

class 斜方肌中部 {
    - 内旋器械反向飞鸟
    - 内旋哑铃反向飞鸟
    - 杠铃俯身划船
    + 正手杠铃划船
}

class 斜方肌下部 {
    -外旋器械反向飞鸟
    -外旋哑铃反向飞鸟
    + 正手杠铃划船
}

class 上背肌群 {
    肩袖四肌
    三角肌后束
===
    - L侧平举
    - 俯身哑铃侧平举
    - 正手宽握高位下拉
    - 直臂下拉
}
class 下背肌群 {
    - 直背体前屈
    + 垂直卷腹
    - 十字挺身
    + 空中单车
    ---
    - 直腿杠铃硬拉
    + 垂直卷腹
    - 山羊挺身
    - 器械卷腹
}
 
@enduml